### ISSUE TITLE
Add options output dir in C code

### ISSUE THREAD

**Issue by blackeangel** [HemanthJabalpuri/pacextractor#5]
Hi, please, add output dir optionally. Python have this, shell have this, but C don't have. Why?

**Comment by HemanthJabalpuri** [comment]
> Hi, please, add output dir optionally. Python have this, shell have this, but C don't have. Why?

Hello, I am not good at writing programs for multiple platforms. C needs to be platform specific and paths in different OS are different.

If you have the code to implement the same for all platforms (Windows, Linux and macOS), please feel free to do a Pull Request.

Thanks
Hemanth.J

**Comment by blackeangel** [comment]
> > Hi, please, add output dir optionally. Python have this, shell have this, but C don't have. Why?
> 
> Hello, I am not good at writing programs for multiple platforms. C needs to be platform specific and paths in different OS are different.
> 
> If you have the code to implement the same for all platforms (Windows, Linux and macOS), please feel free to do a Pull Request.
> 
> Thanks Hemanth.J



Nobody forbids using C++17 and higher to implement this function.
I just can’t figure out your code, where you unload data onto the media from memory.

**Comment by HemanthJabalpuri** [comment]
https://github.com/HemanthJabalpuri/pacextractor/blob/c6928866b1a68ca2e831e56abcd5489c4faadb2b/c/pacextractor.c#L99

This is where filename is read.
You have to prepend directory path to it.

**Comment by rifsxd** [comment]
https://github.com/rifsxd/pacextractor

Supports output, better verbose and more importantly blazing fast extraction speeds

**Comment by blackeangel** [comment]
> https://github.com/rifsxd/pacextractor
> 
> Supports output, better verbose and more importantly blazing fast extraction speeds

OK, add all other features of this same tool to your code, except for the output folder. By the way, is it created in your folder if it doesn't exist? And if you don't specify the output folder, the path will be taken from the output file argument and create a folder with the name of the input file next to the input file? Maybe rewrite it in C++?

**Comment by rifsxd** [comment]
> > https://github.com/rifsxd/pacextractor
> > Supports output, better verbose and more importantly blazing fast extraction speeds
> 
> OK, add all other features of this same tool to your code, except for the output folder. By the way, is it created in your folder if it doesn't exist? And if you don't specify the output folder, the path will be taken from the output file argument and create a folder with the name of the input file next to the input file? Maybe rewrite it in C++?

my fork and modifications is way better than this and yes it will create a folder if it doesnt exist -h for more help and no c++ is not needed C is enough but i might make a port anyways cuz i made a golang port too

**Comment by blackeangel** [comment]
> > > https://github.com/rifsxd/pacextractor
> > > Supports output, better verbose and more importantly blazing fast extraction speeds
> > 
> > 
> > OK, add all other features of this same tool to your code, except for the output folder. By the way, is it created in your folder if it doesn't exist? And if you don't specify the output folder, the path will be taken from the output file argument and create a folder with the name of the input file next to the input file? Maybe rewrite it in C++?
> 
> my fork and modifications is way better than this and yes it will create a folder if it doesnt exist -h for more help and no c++ is not needed C is enough but i might make a port anyways cuz i made a golang port too

what's better? Your structure is different from this one, it's smaller, which means it's less informative. You don't have crc16 control either.
Maybe you can write a repacker?

**Comment by rifsxd** [comment]
use my fork and compare with this you will know whats better if you dont understand C language

**Comment by rifsxd** [comment]
> > > > https://github.com/rifsxd/pacextractor
> > > > Supports output, better verbose and more importantly blazing fast extraction speeds
> > > 
> > > 
> > > OK, add all other features of this same tool to your code, except for the output folder. By the way, is it created in your folder if it doesn't exist? And if you don't specify the output folder, the path will be taken from the output file argument and create a folder with the name of the input file next to the input file? Maybe rewrite it in C++?
> > 
> > 
> > my fork and modifications is way better than this and yes it will create a folder if it doesnt exist -h for more help and no c++ is not needed C is enough but i might make a port anyways cuz i made a golang port too
> 
> what's better? Your structure is different from this one, it's smaller, which means it's less informative. You don't have crc16 control either. Maybe you can write a repacker?

this one is bloated with unecessary code, crc16 is not even needed to unpack

**Comment by rifsxd** [comment]
![image](https://github.com/user-attachments/assets/99fa9926-43d2-446b-8a02-b48c6f472bb4)

This is what you call better? lol

**Comment by rifsxd** [comment]
![image](https://github.com/user-attachments/assets/9cf172b5-c9a4-4e13-b4bb-2a036767d817)


this doesnt even show pac meta info

**Comment by blackeangel** [comment]
> 
> this doesnt even show pac meta info

strange, but in theory it should. After all, the code displays information. The functions even have
https://github.com/HemanthJabalpuri/pacextractor/blob/c6928866b1a68ca2e831e56abcd5489c4faadb2b/c/pacextractor.c#L179

https://github.com/HemanthJabalpuri/pacextractor/blob/c6928866b1a68ca2e831e56abcd5489c4faadb2b/c/pacextractor.c#L207

and I also wonder why the author's PacHeader and PartitionHeader are different from yours? After all, the structure of the header data should be the same.

**Comment by blackeangel** [comment]
> 
> This is what you call better? lol

I didn't say what's better. I asked how yours is better. Now it's clear that yours is better in terms of speed. The only question is, at what expense?

**Comment by rifsxd** [comment]
My fork is not from his but the original which is good enough but slow af as this one and doesn't support output dir, I implemented I/O optimization and better pac extraction hemanths fork is just unnecessary bloat

**Comment by rifsxd** [comment]
> > This is what you call better? lol
> 
> I didn't say what's better. I asked how yours is better. Now it's clear that yours is better in terms of speed. The only question is, at what expense?

No expense, it just is fast with no drawbacks

**Comment by HemanthJabalpuri** [comment]
> > this doesnt even show pac meta info
> 
> strange, but in theory it should. After all, the code displays information. The functions even have
> 
> https://github.com/HemanthJabalpuri/pacextractor/blob/c6928866b1a68ca2e831e56abcd5489c4faadb2b/c/pacextractor.c#L179
> 
> https://github.com/HemanthJabalpuri/pacextractor/blob/c6928866b1a68ca2e831e56abcd5489c4faadb2b/c/pacextractor.c#L207
> 
> and I also wonder why the author's PacHeader and PartitionHeader are different from yours? After all, the structure of the header data should be the same.

He didn't used -d flag when executing. That's the reason output is simple.



> My fork is not from his but the original which is good enough but slow af as this one and doesn't support output dir, I implemented I/O optimization and better pac extraction hemanths fork is just unnecessary bloat

@rifsxd Thanks for your contribution to upstream pacextractor and I appreciate your efforts for the same.

@blackeangel I will take a look of rifsxd's code to implement the features that you have requested.

**Comment by rifsxd** [comment]
> > > this doesnt even show pac meta info
> > 
> > 
> > strange, but in theory it should. After all, the code displays information. The functions even have
> > https://github.com/HemanthJabalpuri/pacextractor/blob/c6928866b1a68ca2e831e56abcd5489c4faadb2b/c/pacextractor.c#L179
> > 
> > https://github.com/HemanthJabalpuri/pacextractor/blob/c6928866b1a68ca2e831e56abcd5489c4faadb2b/c/pacextractor.c#L207
> > 
> > and I also wonder why the author's PacHeader and PartitionHeader are different from yours? After all, the structure of the header data should be the same.
> 
> He didn't used -d flag when executing. That's the reason output is simple.
> 
> > My fork is not from his but the original which is good enough but slow af as this one and doesn't support output dir, I implemented I/O optimization and better pac extraction hemanths fork is just unnecessary bloat
> 
> @rifsxd Thanks for your contribution to upstream pacextractor and I appreciate your efforts for the same.
> 
> @blackeangel I will take a look of rifsxd's code to implement the features that you have requested.

Hey you are welcome! I will be soon adding functions to repack with same tool as well soon.

**Comment by HemanthJabalpuri** [comment]
@blackeangel 

Added support with https://github.com/HemanthJabalpuri/pacextractor/commit/147e5531b003c4834352577216929389491d48e2

Close the ticket after checking.

**Comment by blackeangel** [comment]
> 
> This is what you call better? lol
open your repository for issue.
faster doesn't work better.
![image1](https://github.com/user-attachments/assets/566f5cba-ef70-4167-b9a2-aaf476574f66)
![image2](https://github.com/user-attachments/assets/14361621-66f1-4ae4-a734-4fc7c044d134)

screenshots of extracted vbmeta_product.img.

**Comment by rifsxd** [comment]
![image](https://github.com/user-attachments/assets/9fbd55ef-c0f5-4360-982d-ad44b45d904c)

its an issue on your side buddy

**Comment by blackeangel** [comment]
> 
> its an issue on your side buddy

Unlikely. I compiled it from your sources, launched unpacking. What did I do wrong? It was extracted crookedly. So yours does not support all possible images, not all versions, etc.

**Comment by HemanthJabalpuri** [comment]
@blackeangel 

Open an issue in his repo and close this ticket if required feature is fulfilled.
